---
- name: Install pip for Python 2.7 from RHEL
  yum:
    name: 'python2-pip'
    state: present

# Pygments for system wide syntax highlighting with 'ccat' command
- name: Install Pygments for Python 2.7
  pip:
    name: pygments<2.6

- name: Set 'ccat' alias in global bashrc
  lineinfile:
    dest: /etc/bashrc
    line: "{{ item.line }}"
  with_items:
    - { line: '# The line below allows syntax highlighting for files with the command "ccat".' }
    - { line: "alias ccat='pygmentize -O style=monokai -f terminal -g'" }

# Set up Cookie Cutter system-wide
- name: Install Cookie Cutter for Python 2.7
  pip:
    name: cookiecutter   
