---
- name: Install development tools with yum
  yum:
    name: "@Development tools"
    state: present
- name: Remove CentOS git; we'll install git 2.x below
  yum: 
    name: 
      - git
    state: absent
- name: Install git, vim, vind-utils, and dependencies for pip installs with yum
  yum: 
    name:
      - git
      - vim
      - bind-utils
      - zlib-devel
      - sqlite-devel
      - bzip2-devel
      - graphviz-devel
      - openssl-devel
      - libffi-devel
      - libjpeg-turbo-devel
      - giflib
      - tmux
      - libmemcached-devel
    state: present
- name: Install bash completion for git
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: /etc/bash_completion.d/git
    mode: '0644'
