---
- name: Install redis
  yum:
    name: 
      - redis32u
      - python38u-redis
    state: present

- name: Make sure redis is started at boot.
  service:
    name: redis
    enabled: true
    state: started
